apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flak
  name: flak
  namespace: flak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flak-operator
  template:
    metadata:
      labels:
        app: flak-operator
    spec:
      containers:
        - image: ghcr.io/amirhnajafiz/flak-operator:latest
          name: flak-operator-container
          imagePullPolicy: IfNotPresent
          env:
            - name: FLAK_LOG_LEVEL
              value: "debug"
            - name: FLAK_JSON_LOG
              value: "false"
            - name: FLAK_TLS__ENABLE
              value: "true"
          volumeMounts:
            - name: tls
              mountPath: "/etc/flak/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: flak-webhook-tls
